# Generated by Django 5.0.4 on 2024-09-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number_of_outlets', models.IntegerField()),
                ('number_of_employees', models.IntegerField()),
                ('address', models.TextField()),
                ('gts_number', models.CharField(max_length=50)),
            ],
        ),
    ]
