# Generated by Django 5.0.4 on 2024-09-18 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logos/')),
                ('gst_number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('account_details', models.TextField()),
                ('outlet_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlets', to='myapp.company')),
            ],
        ),
    ]
